package nobitex

type GetWalletsResponse struct {
	Status  string   `json:"status"`
	Wallets []Wallet `json:"wallets"`
}

type Wallet struct {
	DepositAddress  *string                `json:"depositAddress"`
	DepositTag      interface{}            `json:"depositTag"`
	DepositInfo     map[string]DepositInfo `json:"depositInfo"`
	ID              int64                  `json:"id"`
	Currency        string                 `json:"currency"`
	Balance         string                 `json:"balance"`
	BlockedBalance  string                 `json:"blockedBalance"`
	ActiveBalance   string                 `json:"activeBalance"`
	RialBalance     int64                  `json:"rialBalance"`
	RialBalanceSell int64                  `json:"rialBalanceSell"`
}

type DepositInfo struct {
	Address *string     `json:"address"`
	Tag     interface{} `json:"tag"`
} // Generated by https://quicktype.io

type GetWalletsByCurrencyResponse struct {
	Status  string                      `json:"status"`
	Wallets map[string]WalletByCurrency `json:"wallets"`
}

type WalletByCurrency struct {
	ID      int64  `json:"id"`
	Balance string `json:"balance"`
	Blocked string `json:"blocked"`
}

type MarketStatsResponse struct {
	Status string                 `json:"status"`
	Stats  map[string]MarketStats `json:"stats"`
}

type MarketStats struct {
	IsClosed  bool   `json:"isClosed"`
	BestSell  string `json:"bestSell"`
	BestBuy   string `json:"bestBuy"`
	VolumeSrc string `json:"volumeSrc"`
	VolumeDst string `json:"volumeDst"`
	Latest    string `json:"latest"`
	Mark      string `json:"mark"`
	DayLow    string `json:"dayLow"`
	DayHigh   string `json:"dayHigh"`
	DayOpen   string `json:"dayOpen"`
	DayClose  string `json:"dayClose"`
	DayChange string `json:"dayChange"`
}
