package nobitex

type GetWalletsResponse struct {
	Status  string   `json:"status"`
	Wallets []Wallet `json:"wallets"`
}

type Wallet struct {
	DepositAddress  *string                `json:"depositAddress"`
	DepositTag      interface{}            `json:"depositTag"`
	DepositInfo     map[string]DepositInfo `json:"depositInfo"`
	ID              int64                  `json:"id"`
	Currency        string                 `json:"currency"`
	Balance         string                 `json:"balance"`
	BlockedBalance  string                 `json:"blockedBalance"`
	ActiveBalance   string                 `json:"activeBalance"`
	RialBalance     int64                  `json:"rialBalance"`
	RialBalanceSell int64                  `json:"rialBalanceSell"`
}

type DepositInfo struct {
	Address *string     `json:"address"`
	Tag     interface{} `json:"tag"`
} // Generated by https://quicktype.io

type GetWalletsByCurrencyResponse struct {
	Status  string                      `json:"status"`
	Wallets map[string]WalletByCurrency `json:"wallets"`
}

type WalletByCurrency struct {
	ID      int64  `json:"id"`
	Balance string `json:"balance"`
	Blocked string `json:"blocked"`
}
